#!/bin/bash

VERSION=0.7.2.2911
SCALA_VERSION=2.9.1-1

# copy all jars

#cp \
#	$(find lib_managed project/boot/scala-$SCALA_VERSION core/lib_managed/scala_$SCALA_VERSION/compile -name \*.jar) \
#	debian/usr/lib/kafka

# copy a reference of the latest config files

#cp debian/etc/kafka/log4j.properties debian/etc/kafka/server.properties debian/usr/share/doc/kafka

#dpkg -b debian kafka-$VERSION.deb

debuild -us -uc
